version: '3.7'

services:
  prod:
    container_name: prod
    tty: true
    build:
      context: ./
      dockerfile: prod.Dockerfile
    ports:
      - 8082:8082
    environment:
      SERVER_PORT: 8082
      SESSION_KEY: DONT_FORGET_TO_CHANGE_IT
  dev:
    container_name: dev
    tty: true
    build:
      context: ./docker
    volumes:
      - ./:/app
    ports:
      - 8083:8083
    environment:
      SERVER_PORT: 8083
      SESSION_KEY: DONT_FORGET_TO_CHANGE_IT