version: '3.7'

services:
  golang:
    container_name: golang
    tty: true
    build:
      context: ./docker
    volumes:
      - ./:/app
    ports:
      - 8083:8083
    environment:
      SERVER_PORT: 8083
      SESSION_KEY: DONT_FORGET_TO_CHANGE_IT
